### ISSUE TITLE
> 还有一个地方忘记说了，将代码中的Queue.Queue改为Queue，可以全文检索一下，好像一共2处

### ISSUE THREAD

**Issue by POP-930** [dr0op/bufferfly#5]
> 还有一个地方忘记说了，将代码中的Queue.Queue改为Queue，可以全文检索一下，好像一共2处

这个程序好像修复了也没法正常使用呀，运行命令倒是不报错了，可运行完什么也不返回

_Originally posted by @xslzlccc in https://github.com/dr0op/bufferfly/issues/2#issuecomment-955637986_而且运行出来的，有乱码的现象

**Comment by zyyszds** [comment]
Traceback (most recent call last):
  File "bufferflic.py", line 31, in <module>
    urlQueue = Queue(1000*100)
TypeError: 'module' object is not callable 师傅，改了之后还是报这个错误是为啥

**Comment by zyyszds** [comment]
没改之前报这个错误

**Comment by zyyszds** [comment]
Traceback (most recent call last):
  File "bufferflic.py", line 36, in <module>
    lineQueue = Queue(1000*100)
TypeError: 'module' object is not callable
